config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root "home#index"
  
  resources :gacha_items, only: %i[new index show] do
    collection do
      post :draw
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gacha_item.rb
class GachaItem < ApplicationRecord
  has_many :user_gachas, dependent: :destroy
  has_many :users, through: :user_gachas

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_gachas
  has_many :gacha_items, through: :user_gachas
end

app/models/user_gacha.rb
class UserGacha < ApplicationRecord
  belongs_to :user
  belongs_to :gacha_item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  add_flash_types :success, :danger

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if session[:pending_gacha_item_id]
      UserGacha.create(user: current_user, gacha_item_id: session[:pending_gacha_item_id])
      session.delete(:pending_gacha_item_id)
    end

    super
  end

  private

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/gacha_items_controller.rb
class GachaItemsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def new
  end

  def draw
    @gacha_item = GachaItem.order("RANDOM()").first

    if current_user
      UserGacha.create(user: current_user, gacha_item: @gacha_item)
    else
      session[:pending_gacha_item_id] = @gacha_item.id
    end
      redirect_to gacha_item_path(@gacha_item)
  end

  def show
    @gacha_item = GachaItem.find(params[:id])
    if current_user
      unless current_user.gacha_items.exists?(id: @gacha_item.id)
        redirect_to root_path, danger: "権限がありません"
      end
    else
      unless session[:pending_gacha_item_id] == @gacha_item.id
        redirect_to root_path, danger: "権限がありません（ゲスト）"
      end
    end
  end

  def index
    @gacha_items = current_user.gacha_items.distinct
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      if resource.persisted?
      flash[:success] = "登録に成功しました"
      else
      flash.now[:danger] = "登録に失敗しました。入力内容を確認してください"
      end
    end
  end

  def new
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
  end

  def create
    self.resource = warden.authenticate(auth_options)
    if resource
      flash[:success] = "ログインに成功しました"
      sign_in(resource_name, resource)
      redirect_to root_path
    else
      flash.now[:danger] = "EmailかPasswordが違います"
      render :new, status: :unprocessable_entity
    end
  end



  def destroy
    sign_out(current_user)
    redirect_to new_user_session_path, success: "ログアウトに成功しました"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gacha_items_helper.rb
module GachaItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gacha_items/index.html.erb
<div class="flex flex-wrap w-[1000px] mx-auto items-center">

  <% @gacha_items.each do |item| %>
    <div class="w-125 h-auto bg-blue-200 border p-25 mt-10">
      <%= image_tag("/images/#{item.gacha_image}", class: "") if item.gacha_image.present? %>
      <div class="mt-5 font-bold text-xl">
      <%= "#{item.name}"  %>
      </div>
      <div class="mt-5 border p-5 bg-black text-white font-bold">
      <%= "#{item.body}" %>
      </div>
    </div>
  <% end %>

</div>

app/views/gacha_items/new.html.erb
<div class="flex flex-col items-center justify-center h-screen">
    <p class="mt-20 text-xl p-10 text-black">今日は誰に出会えるだろうか</p>
    <%= link_to "ガチャを引く", draw_gacha_items_path,
     data: { turbo_method: :post },
     class: "mt-20 text-xl bg-black p-10 text-white hover:opacity-60 transition duration-300 rounded-lg" %>
</div>

app/views/gacha_items/show.html.erb
<div class="flex flex-col items-center justify-center">

<div x-data="{ show: true }" x-init="setTimeout(() => show = false, 300)" class="relative">

    <!-- 白いオーバーレイ -->
  <div x-show="show"
       x-transition.opacity.duration.2500ms
       class="fixed inset-0 bg-[#fffbe6] z-50">
   </div>

  </div>

    <div class=" bg-blue-200 border p-25 mt-30">
    <%= image_tag("/images/#{@gacha_item.gacha_image}", class: "w-180 h-auto") if @gacha_item.gacha_image.present? %>
    <div class="mt-5 font-bold text-xl">
    <%= "#{@gacha_item.name}" %>
    </div>
    <div class="w-180 mt-5 border p-5 bg-black text-white font-bold">
    <%= "#{@gacha_item.body}" %>
    </div>
</div>

<% if current_user %>
<%= link_to "自分の友達を見に行く", gacha_items_path, class: "mt-20 text-xl bg-black p-10 text-white hover:opacity-60 transition duration-300 rounded-lg" %>
<% else %>
<%= link_to "登録してコレクションにする", new_user_registration_path, class: "mt-20 text-xl bg-black p-10 text-white hover:opacity-60 transition duration-300 rounded-lg" %>
<% end %>
    
  <%= link_to "Xでシェア", "https://twitter.com/intent/tweet?url=#{CGI.escape('https://gachaapp-2.onrender.com')}&text=#{CGI.escape("#{@gacha_item.name}を引きました！次は誰に会えるんだろう？")}", target: "_blank", rel: "noopener", class: "mt-20 mb-10 text-xl bg-black p-10 text-white hover:opacity-60 transition duration-300 rounded-lg" %>

</div>

app/views/home/index.html.erb
<div class="flex flex-col items-center justify-center h-screen mx-auto ">
<div class="mb-30 text-xl">
  エラーと友達になりますか？
</div>
  <% if current_user %>
    <%= link_to "ガチャを引く", new_gacha_item_path, class: "text-xl bg-black p-10 text-white hover:opacity-60 transition duration-300 rounded-lg" %>
    <div class="mt-30">
    <%= link_to "自分の友達を見に行く", gacha_items_path, class: "text-xl bg-black p-10 text-white hover:opacity-60 transition duration-300 rounded-lg" %>
    </div>
 <% else %>
    <%= link_to "ゲストでガチャを引く", new_gacha_item_path, class: "text-xl bg-black p-10 text-white hover:opacity-60 transition duration-300 rounded-lg" %>
    <div class="mt-30">
    <%= link_to "登録ページ", new_user_registration_path, class: "text-xl bg-black p-10 text-white hover:opacity-60 transition duration-300 rounded-lg" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "GachaApp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'shared/header' %>

  <div style="background-image: url(<%= asset_path('bg-pic.png') %>);" class="bg-cover">

<% flash.each do |type, message| %>
  <div class="p-4 mb-4 rounded text-center <%= { success: 'bg-green-100', danger: 'bg-red-300' }[type.to_sym] %>">
    <%= message %>
  </div>
<% end %>

    <%= yield %>
     <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-black text-white p-4 flex justify-between items-center">
 
</footer>

app/views/shared/_header.html.erb
<header class="bg-gray-800 text-white p-4 flex justify-between items-center">
  <h1 class="text-xl font-bold ml-15">
    <% if current_user %>
    あなたは<%= current_user.nickname %>です
    <% else %>
    あなたはゲストです
    <% end %>
    </h1>

  <!-- ハンバーガーメニュー -->
  <div x-data="{ open: false }" class="relative">
    <!-- 三本線ボタン -->
    <button @click="open = !open" class="focus:outline-none">
      <!-- 三本線 -->
      <svg class="w-6 h-6 mr-15" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
          d="M4 6h16M4 12h16M4 18h16" />
      </svg>
    </button>

    <!-- メニュー内容 -->
    <div x-show="open" @click.outside="open = false" class="absolute right-0 mt-2 w-48 bg-white text-black rounded shadow-lg">
      <%= link_to "ホーム", root_path, class: "block px-4 py-2 hover:bg-gray-100" %>
      <% if current_user %>
        <%= link_to "ログアウト", destroy_user_session_path, 
            data: { turbo_method: :delete, turbo_confirm: "本当にログアウトしますか？" }, 
            class: "block px-4 py-2 hover:bg-gray-100" %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "block px-4 py-2 hover:bg-gray-100" %>
      <% end %>
    </div>
  </div>
</header>